### ISSUE TITLE
Scrolling too far left causes crash

### ISSUE THREAD

**Issue by ProfessorStoke** [rpandey1234/Covid19Tracker#2]
Steps to repeat:

1. Select Alaska in state drop down.
2. Drag finger to left side of graph past March 11th and the app crashes.

This doesn't appear to be a problem for the nationwide graphs.

**Comment by rpandey1234** [comment]
Wow, good catch!! I fixed it here: https://github.com/rpandey1234/Covid19Tracker/commit/0c373f5ccfa889be1b54452c5efb0050fed85255

I also created a new 1.1 release which includes both the issues you've identified, if you'd like to download the APK on your phone again: https://github.com/rpandey1234/Covid19Tracker/releases/tag/1.1

Thanks for reporting 🥰
